Repository GSG-G10/Housy, pull requests merged in 2021-11, with the labels that each got.

#65 Development
  server/app.js
  server/controllers/estates/deleteEstate.js
  server/controllers/estates/editEstate.js
  server/controllers/estates/index.js
  server/controllers/index.js
  server/controllers/users/getAllUsers.js
  server/controllers/users/index.js
  server/controllers/users/login.js
  server/controllers/users/signup.js
  server/database/config/connection.js
  server/database/config/fakeData.sql
  server/database/quieres/account/signUp.js
  server/database/quieres/checkAdmin.js
  server/database/quieres/checkEmailQuery.js
  server/database/quieres/deleteEstateQuery.js
  server/database/quieres/editEstatesQuery.js
  server/database/quieres/index.js
  server/middleware/index.js
  server/middleware/isAdmin.js
  server/routes/auth.js
  server/routes/estate.js
  server/routes/index.js
  server/routes/users.js
  server/test/index.test.js
  server/utils/validation/agentSchema.js
  server/utils/validation/editEstateValidation.js
  server/utils/validation/loginSchema.js
Labels: Awaiting Review

#70 sign up as admin
  server/controllers/admins/index.js
  server/controllers/admins/signupAdmin.js
  server/controllers/logout.js
  server/database/quieres/index.js
  server/database/quieres/signUpAdminQuery.js
  server/routes/admin.js
  server/routes/index.js
  server/test/index.test.js
  server/utils/validation/adminSchema.js
Labels: Done

#71 create end point to login admin #69
  server/controllers/admins/index.js
  server/controllers/admins/login.js
  server/controllers/index.js
  server/routes/admin.js
  server/routes/users.js
  server/test/index.test.js
Labels: Awaiting Review

#73 footer
  client/package.json
  client/src/App.js
  client/src/assets/facebook.png
  client/src/assets/homeIcon.png
  client/src/components/Footer/Footer.js
  client/src/components/Footer/footer.css
  client/src/index.js
Labels: Awaiting Review

#67 PUT || Edit User
  server/controllers/index.js
  server/controllers/users/index.js
  server/controllers/users/login.js
  server/controllers/users/putAgent.js
  server/controllers/users/signup.js
  server/database/config/fakeData.sql
  server/database/quieres/account/signUp.js
  server/database/quieres/index.js
  server/database/quieres/putAgent.js
  server/routes/auth.js
  server/routes/estate.js
  server/routes/index.js
  server/routes/users.js
  server/test/index.test.js
  server/utils/tokenFunction.js
  server/utils/validation/editAgentSchema.js
Labels: Awaiting Review

#86 85 edit fake data
  client/src/App.js
  client/src/components/Footer/Footer.js
  client/src/components/Footer/data.js
  client/src/components/Footer/index.js
  client/src/components/Footer/style.css
  client/src/components/Search/index.js
  client/src/components/Search/style.css
  client/src/components/index.js
  package.json
  server/controllers/users/putAgent.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/fakeData.sql
  server/test/admins.test.js
  server/test/agents.test.js
  server/test/estates.test.js
Labels: Awaiting Review

#77 53 user contact card
  client/package.json
  client/src/App.js
  client/src/assets/profile-picture.jpg
  client/src/components/UserContacatCard/index.js
  package.json
  test.js
Labels: Awaiting Review

#74 create navbar component with style #40
  client/src/App.js
  client/src/asstes/avatar.png
  client/src/asstes/logo.png
  client/src/components/Navbar/index.js
  client/src/components/Navbar/style.css
Labels: Awaiting Review

#81 80 edit query
  server/controllers/users/userEstates.js
  server/database/quieres/agentQuery.js
  server/database/quieres/index.js
  server/database/quieres/userEstatesQuiery.js
Labels: Awaiting Review, Back End

#84 property card
  client/src/App.js
  client/src/assets/bath.png
  client/src/assets/beds.png
  client/src/assets/rooms.png
  client/src/assets/space.png
  client/src/components/PropertyCard/PropertyCard.css
  client/src/components/PropertyCard/index.js
  package.json
Labels: Awaiting Review

#91 90 get estate quer
  client/src/App.js
  client/src/assets/background.png
  client/src/pages/Estate/estate.css
  client/src/pages/Estate/index.js
  server/controllers/estates/getEstate.js
  server/controllers/estates/index.js
  server/controllers/index.js
  server/database/quieres/getEstateQuery.js
  server/database/quieres/getImagesQuery.js
  server/database/quieres/index.js
  server/routes/estate.js
Labels: Awaiting Review

#92 estate : add endpoint search
  server/controllers/estates/filterEstate.js
  server/controllers/estates/index.js
  server/controllers/index.js
  server/database/quieres/filterEstates.js
  server/database/quieres/index.js
  server/routes/estate.js
  server/test/estates.test.js
Labels: Awaiting Review

#93 create login component #64
  client/package.json
  client/src/App.js
  client/src/assets/Iconfacebook.png
  client/src/assets/Icongoogle.png
  client/src/components/Navbar/index.js
  client/src/components/login/index.jsx
  client/src/components/login/style.css
Labels: Awaiting Review

#79 create profile page with components and style #55
  client/.gitignore
  client/src/assetes/house.jpeg
  client/src/components/Agent/EstateAgent/index.jsx
  client/src/components/Agent/EstateAgent/style.css
  client/src/components/Agent/Favroit/index.jsx
  client/src/components/Agent/Info/index.jsx
  client/src/components/Agent/PenddingEstate/index.jsx
  client/src/components/Agent/static/index.jsx
  client/src/components/tab/index.jsx
  client/src/pages/Profile/index.jsx
  package.json
Labels: Awaiting Review, Front End

#96 create component for link #95
  client/src/assets/avatar.png
  client/src/assets/logo.png
  client/src/components/Navbar/index.js
  client/src/components/common/LinkComponent/index.jsx
Labels: Awaiting Review

#94 result search page : create & design
  client/.eslintrc.json
  client/.gitignore
  client/src/App.js
  client/src/assets/Solid.svg
  client/src/assets/Vector.svg
  client/src/assets/bath.png
  client/src/assets/beds.png
  client/src/assets/couch.png
  client/src/assets/foreground.png
  client/src/assets/image.jpg
  client/src/assets/index.js
  client/src/assets/marker.svg
  client/src/assets/money.png
  client/src/assets/money.svg
  client/src/components/CardHouse/index.js
  client/src/components/CardHouse/style.css
  client/src/components/Search/index.js
  client/src/components/Search/style.css
  client/src/components/SearchPgComponent/CardsSection.js
  client/src/components/SearchPgComponent/FilterSide.js
  client/src/components/SearchPgComponent/SearchSection.js
  client/src/components/SearchPgComponent/index.js
  client/src/components/SearchPgComponent/style.css
  client/src/components/index.js
  client/src/pages/resultSearch.jsx
  client/src/utils/truncateFun.js
  server/controllers/estates/filterEstate.js
  server/database/quieres/filterEstates.js
Labels: Awaiting Review
