Repository GSG-G10/Housy, pull requests merged in 2021-10, with the labels that each got.

#36 12 get estates
  server/controllers/estates/allEstate.js
  server/controllers/estates/editEstate.js
  server/controllers/estates/index.js
  server/controllers/index.js
  server/controllers/users/userEstates.js
  server/database/quieres/editEstatesQuery.js
  server/database/quieres/getAllEstateQuery.js
  server/database/quieres/index.js
  server/routes/index.js
  server/test/index.test.js
Labels: Done

#25 SignUp As Agent
  server/controllers/users/index.js
  server/controllers/users/signup.js
  server/database/config/connection.js
  server/database/config/fakeData.sql
  server/database/quieres/account/signUp.js
  server/routes/auth.js
  server/routes/estate.js
  server/routes/index.js
  server/routes/users.js
  server/test/index.test.js
  server/utils/validation/agentSchema.js
Labels: Changes Requested

#35 DELETE || ESTATE
  server/controllers/estates/deleteEstate.js
  server/controllers/estates/index.js
  server/controllers/index.js
  server/database/quieres/deleteEstate.js
  server/database/quieres/index.js
  server/routes/auth.js
  server/routes/estate.js
  server/routes/index.js
  server/routes/users.js
  server/test/index.test.js
Labels: Awaiting Review

#34 edit estate function and update query
  server/controllers/estates/deleteEstate.js
  server/controllers/estates/editEstate.js
  server/controllers/estates/index.js
  server/controllers/index.js
  server/database/config/connection.js
  server/database/quieres/deleteEstateQuery.js
  server/database/quieres/editEstatesQuery.js
  server/database/quieres/index.js
  server/routes/estate.js
  server/routes/index.js
  server/test/index.test.js
  server/utils/validation/editEstateValidation.js
Labels: Awaiting Review

#33 create end point login #15
  server/controllers/index.js
  server/controllers/users/getAllUsers.js
  server/controllers/users/index.js
  server/controllers/users/login.js
  server/database/config/fakeData.sql
  server/database/quieres/checkEmailQuery.js
  server/database/quieres/index.js
  server/routes/auth.js
  server/routes/index.js
  server/test/index.test.js
  server/utils/validation/loginSchema.js
Labels: Awaiting Review

#39 create authentication to admin #37
  server/database/quieres/checkAdmin.js
  server/database/quieres/index.js
  server/middleware/index.js
  server/middleware/isAdmin.js
Labels: Awaiting Review
